version: "3.2"
services:
  authserver:
    image: anthonyikeda/authserver:latest
    container_name: authserver
    environment:
      - SPRING_SECURITY_PASSWORD=vagrant
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:13306/auth_db
      - SPRING_CLOUD_VAULT_HOST=vault1
      - SPRING_CLOUD_VAULT_SCHEME=http
      - SPRING_CLOUD_VAULT_AUTHENTICATION=approle
      - SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID=152d5169-66ad-2396-b158-daa9482ba352
      - SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID=ca534f3e-b1a6-a442-ed24-dbb03e818a5d
      - SPRING_CLOUD_VAULT_MYSQL_ENABLED=true
      - SPRING_CLOUD_VAULT_MYSQL_ROLE=cloud-auth
      - SPRING_CLOUD_VAULT_MYSQL_BACKEND=mysql
      - SPRING_CLOUD_VAULT_MYSQL_USERNAME_PROPERTY=spring.datasource.username
      - SPRING_CLOUD_VAULT_MYSQL_PASSWORD_PROPERTY=spring.datasource.password
      - SECURITY_OAUTH2_CLIENT_CLIENT_ID=sample
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=password
    external_links:
      - vault

networks:
  default:
    external:
      name: cloud-dev
