version: "3.2"
services:
  departmentapi:
    image: anthonyikeda/department-api:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=vagrant
      - SERVER_PORT=8082
      - SPRING_CLOUD_CONSUL_HOST=consul1
      - SPRING_CLOUD_VAULT_HOST=vault1
      - SPRING_CLOUD_VAULT_SCHEME=http
      - SPRING_CLOUD_VAULT_AUTHENTICATION=APPROLE
      - SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID=ac23c1a4-97a9-1c74-7279-178a6de68091
      - SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID=26454e85-ec92-c37e-f2a5-fc25dee79b2f
      - SPRING_CLOUD_VAULT_MYSQL_ENABLED=true
      - SPRING_CLOUD_VAULT_MYSQL_ROLE=cloud-auth
      - SPRING_CLOUD_VAULT_MYSQL_BACKEND=department-database
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:13306/department_db
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://authserver:9090/user
      - SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI=http://authserver:9090/oauth/check_token"
      - AUTH_SERVER_URL=http://authserver:9090/oauth/check_token
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - LIQUIBASE_CHANGE_LOG=classpath:/db/changelog/db.changelog-master.yml

    external_links:
      - consul
      - vault

networks:
  default:
    external:
      name: cloud-dev
