version: "3.2"
services:
  employeeapi:
    image: anthonyikeda/employee-api:1.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=vagrant
      - SERVER_PORT=8081
      - SPRING_CLOUD_CONSUL_HOST=consul1
      - SPRING_CLOUD_VAULT_HOST=vault1
      - SPRING_CLOUD_VAULT_SCHEME=http
      - SPRING_CLOUD_VAULT_AUTHENTICATION=APPROLE
      - SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID=48a8b769-6a10-1feb-b8e9-51337018468d
      - SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID=0f3a6462-ab22-9cec-0a49-816b5f77c418
      - SPRING_CLOUD_VAULT_MYSQL_ENABLED=true
      - SPRING_CLOUD_VAULT_MYSQL_ROLE=cloud-auth
      - SPRING_CLOUD_VAULT_MYSQL_BACKEND=employee-database
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:13306/employee_db
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://authserver:9090/user"
      - SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI=http://authserver:9090/oauth/check_token
      - AUTH_SERVER_URL=http://authserver:9090/oauth/check_token
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - LIQUIBASE_CHANGE_LOG=classpath:/db/changelog/db.changelog-master.yaml
    external_links:
      - consul
      - vault

networks:
  default:
    external:
      name: cloud-dev
