version: "3.2"
services:
  employeeapi:
    image: anthonyikeda/employee-api:1.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=vagrant
      - SERVER_PORT=8081
      - SPRING_CLOUD_CONSUL_HOST=consul1
      - SPRING_CLOUD_VAULT_HOST=vault1
      - SPRING_CLOUD_VAULT_SCHEME=http
      - SPRING_CLOUD_VAULT_AUTHENTICATION=APPROLE
      - SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID=439ebf28-49ac-7a5f-42c2-d47f7d4ae110
      - SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID=350fec14-f999-45b2-050d-c0e312d2e579
      - SPRING_CLOUD_VAULT_MYSQL_ENABLED=true
      - SPRING_CLOUD_VAULT_MYSQL_ROLE=cloud-auth
      - SPRING_CLOUD_VAULT_MYSQL_BACKEND=employee-database
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:13306/employee_db
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://authserver:9090/user
      - SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI=http://authserver:9090/oauth/check_token
      - AUTH_SERVER_URL=http://authserver:9090/oauth/check_token
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - LIQUIBASE_CHANGE_LOG=classpath:/db/changelog/db.changelog-master.yaml
    external_links:
      - consul
      - vault

networks:
  default:
    external:
      name: cloud-dev
